### PR TITLE
hande plot_network/get interactions more gracefully #259

### LINKED ISSUE #244: `analyse_functional_network()` update default version
Dear colleagues,

it would be nice if you could update the STRINGdb default version from 11.5 to 12.0.

Thanks a lot,

Anna

### LINKED ISSUE #259: Make package fail gracefully

### PR DESCRIPTION
**Pull request by elena-krismer**
closes #259 
closes #244

### CODE REVIEW

File: R/analyse_functional_network.R [hunk 1]
```diff
@@ -147,36 +164,31 @@ does not match the number of rows in your data.", prefix = "\n", initial = ""))
...
-        dplyr::filter({{ binds_treatment }}) %>%
-        dplyr::mutate(color = "#5680C1")
-    } else {
-      coloring <- input %>%
-        dplyr::filter({{ binds_treatment }}) %>%
-        dplyr::mutate(color = halo_color)
-    }
+    coloring <- input %>%
+      dplyr::filter({{ binds_treatment }}) %>%
+      dplyr::mutate(color = if (missing(halo_color)) "#5680C1" else halo_color)
```
Comment (jpquast) [inline R/analyse_functional_network.R:170]: You cannot use the `missing()` function within `mutate()`. I think it is because `halo_color` is treated as a column name in this case and not as an argument. Not sure if there is a way around this.

**Comment by jpquast** [comment]
Could you please also fix issue #244 within this PR? Not sure if there is by now a newer version than 12. Could you also write the changes and fixes into the `NEWS.md` file.

File: R/analyse_functional_network.R (hunk 1 above)
Comment (elena-krismer) [reply R/analyse_functional_network.R]: yes saw it - didnt had time to check the guthub action before  thanks!

File: R/analyse_functional_network.R [hunk 2]
```diff
@@ -147,36 +165,40 @@ does not match the number of rows in your data.", prefix = "\n", initial = ""))
...
       colors = coloring$color
     )
   }
-  if (plot == TRUE) {
-    if (length(unique(dplyr::pull(data, !!ensym(protein_id)))) > 400) {
-      stop(strwrap("Please only provide the top 400 significant proteins for plots! String
-cannot plot more at once.", prefix = "\n", initial = ""))
+
+
+  tryCatch(
```
Comment (jpquast) [inline R/analyse_functional_network.R:182]: I just noticed that the `return()` at the end doesn't return from the overall function if an error occurs but just from the `try_catch()`. So you cannot actually use it like this within the function. Only works because it is at the end. This is important for the comment above. 
My solution would the following. Maybe you have another idea.
```
interactions <- tryCatch(
    {
      if (plot) {
        string_db$plot_network(string_ids, payload_id = payload_id)
      } else {
        mapping <- input %>%
          dplyr::distinct({{ protein_id }}, {{ string_id }})

        string_db$get_interactions(string_ids) %>%
          dplyr::left_join(mapping, by = c("from" = rlang::as_name(rlang::enquo(string_id)))) %>%
          dplyr::rename(from_protein = {{ protein_id }}) %>%
          dplyr::left_join(mapping, by = c("to" = rlang::as_name(rlang::enquo(string_id)))) %>%
          dplyr::rename(to_protein = {{ protein_id }}) %>%
          dplyr::distinct()
      }
    },
    error = function(e) {
      e$message
    }
  )

  if (is.character(interactions)) {
    message("An error occurred during the interaction network analysis: ", interactions)
    return(invisible(NULL))
  } else {
    return(interactions)
  }
```

**Review by jpquast — CHANGES_REQUESTED** [review]
Doesn't fail gracefully yet (see comments). You can check if it works by turning off your internet.

File: R/analyse_functional_network.R [hunk 3]
```diff
@@ -121,23 +121,60 @@ analyse_functional_network <- function(data,
...
+      STRINGdb$new(
+        version = version,
+        species = organism_id, # Check on String database to get the right code (E.coli K12: 511145)
+        score_threshold = score_threshold, # Cutoff score to consider something an interaction
+        input_directory = ""
+      )
+    },
+    error = function(e) {
+      e$message
+    }
```
Comment (jpquast) [inline R/analyse_functional_network.R:170]: Can you also catch the warning message here. You don't need to include the resulting message, but just not have it return the warning.

**Review by jpquast — CHANGES_REQUESTED** [review]

File: R/analyse_functional_network.R (hunk 3 above)
Comment (elena-krismer) [reply R/analyse_functional_network.R]: should we print this part ("A warning occurred during the interaction network analysis: " or not?
 :)

Comment (jpquast) [reply R/analyse_functional_network.R]: yes looks good like this actually! Thanks! :)

**Review by jpquast — APPROVED** [review]
Looks good now! 🥇
